sonar.projectKey=olxgdm_cfgsync
sonar.organization=olxgdm

sonar.projectVersion=0.2.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=build/**,install/**,bw-output/**
sonar.cfamily.llvm-cov.reportPath=build/coverage/llvm-cov.txt
